name: go-rest
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    networks:
      - go-compose-net
    ports:
      - 9000:9000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.39
    ports:
      - 3306:3306
    env_file:
      - .env.db-root-cred
      - .env.db-user
    volumes:
      - type: volume
        source: go-rest-data
        target: /var/lib/mysql
    networks:
      - go-compose-net
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 2

volumes:
  go-rest-data:

networks:
  go-compose-net:
